# Generated by Django 5.0.4 on 2024-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=100)),
                ('hotelPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotelAvailability', models.BooleanField(default=False)),
            ],
        ),
    ]
